---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: read-secrets-global
subjects:
- kind: ServiceAccount
  name: pesto-informer
  namespace: mynamespace
roleRef:
  kind: ClusterRole
  name: informer-role
  apiGroup: rbac.authorization.k8s.io
