---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: informer-role
rules:
- apiGroups: ["apps/v1"]
  resources: ["deployments"]
  verbs: ["get", "watch", "list"]
# - apiGroups: ["apps/v1"]
#   resources: ["openbao-vaults"]
#   verbs: ["get", "watch", "list"]
